import type { Metadata } from "next";
import { Montserrat, Red_Hat_Display } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";
import "leaflet/dist/leaflet.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const redHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"
        />
      </head>
      <body className={`${redHatDisplay.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
